apiVersion: v1
kind: Service
metadata:
  name: simpleserve
  labels:
    app: simpleserve
spec:
  type: NodePort
  selector:
    app: simpleserve
  ports:
    - port: 8000
      name: http
      targetPort: 8000
      nodePort: 30008
